# Generated by Django 5.0.6 on 2025-06-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_genre_alter_movie_poster_url_moviegenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', through='movie.MovieGenre', to='movie.genre'),
        ),
    ]
